"""GitHub Brood auth

Revision ID: 0c9b33f440d1
Revises: cfe55041d49f
Create Date: 2020-12-01 10:42:15.507815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c9b33f440d1'
down_revision = 'cfe55041d49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_bugout_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('bugout_user_id', sa.String(), nullable=False),
    sa.Column('bugout_access_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['github_oauth_events.id'], name=op.f('fk_github_bugout_users_event_id_github_oauth_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_bugout_users')),
    sa.UniqueConstraint('id', name=op.f('uq_github_bugout_users_id'))
    )
    op.create_unique_constraint(op.f('uq_github_check_notes_id'), 'github_check_notes', ['id'])
    op.create_unique_constraint(op.f('uq_github_checks_id'), 'github_checks', ['id'])
    op.create_unique_constraint(op.f('uq_github_issues_prs_id'), 'github_issues_prs', ['id'])
    op.drop_constraint('uq_github_oauth_events_bugout_holder_id', 'github_oauth_events', type_='unique')
    op.drop_constraint('uq_github_oauth_events_bugout_secret', 'github_oauth_events', type_='unique')
    op.drop_column('github_oauth_events', 'bugout_secret')
    op.drop_column('github_oauth_events', 'bugout_holder_id')
    op.create_unique_constraint(op.f('uq_github_repos_id'), 'github_repos', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_github_repos_id'), 'github_repos', type_='unique')
    op.add_column('github_oauth_events', sa.Column('bugout_holder_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('github_oauth_events', sa.Column('bugout_secret', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_github_oauth_events_bugout_secret', 'github_oauth_events', ['bugout_secret'])
    op.create_unique_constraint('uq_github_oauth_events_bugout_holder_id', 'github_oauth_events', ['bugout_holder_id'])
    op.drop_constraint(op.f('uq_github_issues_prs_id'), 'github_issues_prs', type_='unique')
    op.drop_constraint(op.f('uq_github_checks_id'), 'github_checks', type_='unique')
    op.drop_constraint(op.f('uq_github_check_notes_id'), 'github_check_notes', type_='unique')
    op.drop_table('github_bugout_users')
    # ### end Alembic commands ###
