"""github check id from int to string

Revision ID: 0f655ab65e68
Revises: d63f160eba77
Create Date: 2021-03-19 16:48:24.503272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f655ab65e68'
down_revision = 'd63f160eba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_checks', sa.Column('github_check_id_temp', sa.String(), nullable=True))
    op.execute("UPDATE github_checks SET github_check_id_temp = github_check_id")
    op.drop_column('github_checks', 'github_check_id')
    op.add_column('github_checks', sa.Column('github_check_id', sa.String(), nullable=True))
    op.execute("UPDATE github_checks SET github_check_id = github_check_id_temp")
    op.alter_column("github_checks", "github_check_id", nullable=False)
    op.drop_column('github_checks', 'github_check_id_temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM github_checks")
    op.drop_column('github_checks', 'github_check_id')
    op.add_column('github_checks', sa.Column('github_check_id', sa.Integer(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
