"""Context columns in JournalEntry

Revision ID: 18f599c5f3b8
Revises: 407d0919eeec
Create Date: 2020-10-22 02:03:25.702863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f599c5f3b8'
down_revision = '407d0919eeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('context_id', sa.String(), nullable=True))
    op.add_column('journal_entries', sa.Column('context_type', sa.String(), server_default='bugout', nullable=False))
    op.add_column('journal_entries', sa.Column('context_url', sa.String(), nullable=True))
    op.alter_column('journal_entries', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # Copy title with url to context_url and context_id
    op.execute(
        "UPDATE journal_entries SET context_url = "
        "CASE WHEN title LIKE '%.slack.com/archives/%' THEN title ELSE context_url END;"
    )
    # 1. Split to array: regexp_split_to_array(context_url, E'\\/+')
    # 2. Get length of array: array_upper(regexp_split_to_array(context_url, E'\\/+'), 1)
    # 3. Slice array to last element: (regexp_split_to_array(context_url, E'\\/+'))[<2nd step>]
    # 4. Remove query after ?: (regexp_split_to_array(<3rd step>, E'\\?+'))[1]
    # 5. Remove 'p': regexp_replace(<4th step>, 'p', '')
    op.execute(
        "UPDATE journal_entries SET context_id = "
        "regexp_replace((regexp_split_to_array((regexp_split_to_array(context_url, E'\\\/+'))[array_upper(regexp_split_to_array(context_url, E'\\\/+'), 1)], E'\\\?+'))[1], 'p', '');"
    )
    # Copy start of content to title
    op.execute("UPDATE journal_entries SET title = left(content, 18);")
    # Mark as from slack in context_type
    op.execute(
        "UPDATE journal_entries SET context_type = "
        "CASE WHEN context_url LIKE '%.slack.com/archives/%' THEN 'spire' ELSE context_type END;"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_entries', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('journal_entries', 'context_url')
    op.drop_column('journal_entries', 'context_type')
    op.drop_column('journal_entries', 'context_id')
    # ### end Alembic commands ###
