"""slack_oauth_events added bot_scope

Revision ID: 2019d08b53e8
Revises: 2ba9b9213f3f
Create Date: 2020-08-02 23:21:00.602965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2019d08b53e8'
down_revision = '2ba9b9213f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_events', sa.Column('bot_scope', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_oauth_events', 'bot_scope')
    # ### end Alembic commands ###
