"""Add indices on journal_entries.created_at, journal_entries.updated_at

Revision ID: 245914e1ddf9
Revises: 9cb7e4066cc9
Create Date: 2022-06-15 04:06:49.348792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245914e1ddf9'
down_revision = '9cb7e4066cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_updated_at'), 'journal_entries', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_updated_at'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    # ### end Alembic commands ###
