"""Unique constraint on tags: entry id, tag

Revision ID: 2d33cccbba8a
Revises: 6d16778f1404
Create Date: 2020-08-11 19:07:07.489487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d33cccbba8a'
down_revision = '6d16778f1404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_journal_entry_tags_journal_entry_id_tag', 'journal_entry_tags', ['journal_entry_id', 'tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_journal_entry_tags_journal_entry_id_tag', 'journal_entry_tags', type_='unique')
    # ### end Alembic commands ###
