"""Added deleted field to SlackOAuthEvent model

Revision ID: 30de4bdca25c
Revises: e8353e02c365
Create Date: 2020-08-30 13:27:38.364924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30de4bdca25c'
down_revision = 'e8353e02c365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_events', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE slack_oauth_events SET deleted = false;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_oauth_events', 'deleted')
    # ### end Alembic commands ###
