"""Added deleted column to slack_oauth_events

Revision ID: 3ae6eb3460cf
Revises: 779c56f0e104
Create Date: 2020-08-03 06:43:52.609578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae6eb3460cf'
down_revision = '779c56f0e104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_events', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_oauth_events', 'deleted')
    # ### end Alembic commands ###
