"""go permalinks app

Revision ID: 3efbd7688f59
Revises: e95ba3afcca7
Create Date: 2021-04-13 12:51:23.323180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3efbd7688f59'
down_revision = 'e95ba3afcca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permalink_journal_entries',
    sa.Column('entry_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('journal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('permalink', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('pk_permalink_journal_entries')),
    sa.UniqueConstraint('entry_id', name=op.f('uq_permalink_journal_entries_entry_id')),
    sa.UniqueConstraint('journal_id', 'permalink', name=op.f('uq_permalink_journal_entries_journal_id')),
    sa.UniqueConstraint('permalink', name=op.f('uq_permalink_journal_entries_permalink'))
    )
    op.create_table('permalink_journals',
    sa.Column('journal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('permalink', sa.String(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('pk_permalink_journals')),
    sa.UniqueConstraint('journal_id', name=op.f('uq_permalink_journals_journal_id')),
    sa.UniqueConstraint('permalink', name=op.f('uq_permalink_journals_permalink'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permalink_journals')
    op.drop_table('permalink_journal_entries')
    # ### end Alembic commands ###
