"""soft journal deletion

Revision ID: 413122566dc0
Revises: 471dddb50a12
Create Date: 2021-02-03 13:36:02.318596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413122566dc0'
down_revision = '471dddb50a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('deleted', sa.Boolean(), nullable=True))

    # Manual part
    op.execute("UPDATE journals SET deleted = false")
    op.alter_column('journals', 'deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual part
    op.execute("DELETE FROM journals WHERE deleted = true")

    op.drop_column('journals', 'deleted')
    # ### end Alembic commands ###
