"""slack_index_configurations, foreign key cascades in slack tables

Revision ID: 419fd8c9ae41
Revises: 220ae35229d4
Create Date: 2020-08-14 06:19:06.408366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '419fd8c9ae41'
down_revision = '220ae35229d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_index_configurations',
    sa.Column('slack_oauth_event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('index_name', sa.String(), nullable=False),
    sa.Column('index_url', sa.String(), nullable=False),
    sa.Column('use_bugout_auth', sa.Boolean(), nullable=False),
    sa.Column('use_bugout_client_id', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['slack_oauth_event_id'], ['slack_oauth_events.id'], name='fk_slack_bugout_users_slack_oauth_events_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slack_oauth_event_id', 'index_name', name='pk_slack_index_configurations')
    )
    op.drop_constraint('fk_slack_bugout_users_slack_oauth_events_id', 'slack_bugout_users', type_='foreignkey')
    op.create_foreign_key('fk_slack_bugout_users_slack_oauth_events_id', 'slack_bugout_users', 'slack_oauth_events', ['slack_oauth_event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_slack_mentions_slack_oauth_events_id', 'slack_mentions', type_='foreignkey')
    op.create_foreign_key('fk_slack_mentions_slack_oauth_events_id', 'slack_mentions', 'slack_oauth_events', ['slack_oauth_event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_slack_mentions_slack_oauth_events_id', 'slack_mentions', type_='foreignkey')
    op.create_foreign_key('fk_slack_mentions_slack_oauth_events_id', 'slack_mentions', 'slack_oauth_events', ['slack_oauth_event_id'], ['id'])
    op.drop_constraint('fk_slack_bugout_users_slack_oauth_events_id', 'slack_bugout_users', type_='foreignkey')
    op.create_foreign_key('fk_slack_bugout_users_slack_oauth_events_id', 'slack_bugout_users', 'slack_oauth_events', ['slack_oauth_event_id'], ['id'])
    op.drop_table('slack_index_configurations')
    # ### end Alembic commands ###
