"""slack_mentions.{raw_text -> invocation}

Revision ID: 66677aa07c86
Revises: f66f6217c742
Create Date: 2020-08-04 12:32:06.675492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66677aa07c86'
down_revision = 'f66f6217c742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_mentions', sa.Column('invocation', sa.String(), nullable=False))
    op.drop_column('slack_mentions', 'raw_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_mentions', sa.Column('raw_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('slack_mentions', 'invocation')
    # ### end Alembic commands ###
