"""Updated model: journals, journal entries

Revision ID: 6d16778f1404
Revises: 18550e007a4f
Create Date: 2020-08-11 11:21:54.921979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d16778f1404'
down_revision = '18550e007a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('journal_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name='fk_journal_entries_journals_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('journal_entry_tags',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('journal_entry_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name='fk_journal_entry_tags_journal_entries_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('journals', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint('uc_journals_bugout_user_id_name', 'journals', ['bugout_user_id', 'name'])
    op.drop_column('journals', 'content')
    op.drop_table('journal_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uc_journals_bugout_user_id_name', 'journals', type_='unique')
    op.drop_column('journals', 'name')
    op.drop_table('journal_entry_tags')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
