"""slack_oauth_events added bot_user_id

Revision ID: 779c56f0e104
Revises: 2019d08b53e8
Create Date: 2020-08-02 23:23:54.306977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779c56f0e104'
down_revision = '2019d08b53e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_events', sa.Column('bot_user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_oauth_events', 'bot_user_id')
    # ### end Alembic commands ###
