"""Hard deletes for tags

Revision ID: 77ce57ebc87e
Revises: 181062be1f54
Create Date: 2020-08-12 06:26:07.166462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ce57ebc87e'
down_revision = '181062be1f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entry_tags', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry_tags', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
