"""slack_mentions.responded

Revision ID: 7aaf134cf866
Revises: 66677aa07c86
Create Date: 2020-08-04 12:37:32.236494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aaf134cf866'
down_revision = '66677aa07c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_mentions', sa.Column('responded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_mentions', 'responded')
    # ### end Alembic commands ###
