"""Create slack_oauth_events table

Revision ID: 7ccd3dddf090
Revises: 
Create Date: 2020-08-02 22:39:41.528720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ccd3dddf090'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_oauth_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bot_access_token', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('enterprise_id', sa.String(), nullable=True),
    sa.Column('enterprise_name', sa.String(), nullable=True),
    sa.Column('user_access_token', sa.String(), nullable=True),
    sa.Column('authed_user_id', sa.String(), nullable=True),
    sa.Column('authed_user_scope', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_oauth_events')
    # ### end Alembic commands ###
