"""indexes with journal_id in journal_entries

Revision ID: 7efa423a43d7
Revises: 245914e1ddf9
Create Date: 2022-07-04 18:00:18.746634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7efa423a43d7'
down_revision = '245914e1ddf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('ix_journal_entries_journal_id_created_at', 'journal_entries', ['journal_id', 'created_at'], unique=False)
    op.create_index('ix_journal_entries_journal_id_updated_at', 'journal_entries', ['journal_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_entries_journal_id_updated_at', table_name='journal_entries')
    op.drop_index('ix_journal_entries_journal_id_created_at', table_name='journal_entries')
    # ### end Alembic commands ###
