"""Version number in slack_oauth_events

Revision ID: 823f9ea79a50
Revises: 9be6d71375dc
Create Date: 2020-08-18 09:40:30.470895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823f9ea79a50'
down_revision = '9be6d71375dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_events', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE slack_oauth_events SET version=1')
    op.alter_column('slack_oauth_events', 'version', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_oauth_events', 'version')
    # ### end Alembic commands ###
