"""Hard deletions for all journal tables

Revision ID: 97ce2c81e19b
Revises: 77ce57ebc87e
Create Date: 2020-08-12 06:28:31.782057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ce2c81e19b'
down_revision = '77ce57ebc87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'deleted')
    op.drop_column('journals', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journal_entries', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
