"""Store IP boolean column

Revision ID: 9cb7e4066cc9
Revises: afe0933fe927
Create Date: 2021-10-07 10:44:20.436954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb7e4066cc9'
down_revision = 'afe0933fe927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('humbug_bugout_user_tokens', sa.Column('store_ip', sa.Boolean(), nullable=True))

    # Manual
    op.execute("UPDATE humbug_bugout_user_tokens SET store_ip = false")
    op.alter_column("humbug_bugout_user_tokens", "store_ip", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('humbug_bugout_user_tokens', 'store_ip')
    # ### end Alembic commands ###
