"""Added naming convention

Revision ID: a760c9157e9e
Revises: be20b5a921ed
Create Date: 2020-11-16 03:30:00.518667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a760c9157e9e'
down_revision = 'be20b5a921ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_github_diffs_id'), 'github_diffs', ['id'])
    op.create_unique_constraint(op.f('uq_github_oauth_events_id'), 'github_oauth_events', ['id'])
    op.create_unique_constraint(op.f('uq_github_summaries_id'), 'github_summaries', ['id'])
    op.create_unique_constraint(op.f('uq_slack_bugout_users_id'), 'slack_bugout_users', ['id'])
    op.create_unique_constraint(op.f('uq_slack_mentions_id'), 'slack_mentions', ['id'])
    op.drop_constraint('slack_mentions_id_key', 'slack_mentions', type_='unique')
    op.create_unique_constraint(op.f('uq_slack_oauth_events_id'), 'slack_oauth_events', ['id'])
    op.drop_constraint('slack_oauth_events_id_key', 'slack_oauth_events', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('slack_oauth_events_id_key', 'slack_oauth_events', ['id'])
    op.drop_constraint(op.f('uq_slack_oauth_events_id'), 'slack_oauth_events', type_='unique')
    op.create_unique_constraint('slack_mentions_id_key', 'slack_mentions', ['id'])
    op.drop_constraint(op.f('uq_slack_mentions_id'), 'slack_mentions', type_='unique')
    op.drop_constraint(op.f('uq_slack_bugout_users_id'), 'slack_bugout_users', type_='unique')
    op.drop_constraint(op.f('uq_github_summaries_id'), 'github_summaries', type_='unique')
    op.drop_constraint(op.f('uq_github_oauth_events_id'), 'github_oauth_events', type_='unique')
    op.drop_constraint(op.f('uq_github_diffs_id'), 'github_diffs', type_='unique')
    # ### end Alembic commands ###
