"""Created slack_mentions table

Revision ID: d23173c9fd7e
Revises: 3ae6eb3460cf
Create Date: 2020-08-03 12:54:09.856196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd23173c9fd7e'
down_revision = '3ae6eb3460cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_mentions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('slack_oauth_event_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('thread_ts', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['slack_oauth_event_id'], ['slack_oauth_events.id'], name='fk_slack_mentions_slack_oauth_events_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_mentions')
    # ### end Alembic commands ###
