"""public journals model

Revision ID: e95ba3afcca7
Revises: 0f655ab65e68
Create Date: 2021-03-29 10:20:14.433726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e95ba3afcca7'
down_revision = '0f655ab65e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_users',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('access_token_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('restricted_token_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'restricted_token_id', name=op.f('pk_public_users')),
    sa.UniqueConstraint('access_token_id', name=op.f('uq_public_users_access_token_id')),
    sa.UniqueConstraint('restricted_token_id', name=op.f('uq_public_users_restricted_token_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_public_users_user_id'))
    )
    op.create_table('public_journals',
    sa.Column('journal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public_users.user_id'], name=op.f('fk_public_journals_user_id_public_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('pk_public_journals')),
    sa.UniqueConstraint('journal_id', name=op.f('uq_public_journals_journal_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_journals')
    op.drop_table('public_users')
    # ### end Alembic commands ###
