"""Bugout group id for slack and github

Revision ID: f1755bf67b88
Revises: 0c9b33f440d1
Create Date: 2021-01-25 09:58:29.299529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1755bf67b88'
down_revision = '0c9b33f440d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_bugout_users', sa.Column('bugout_group_id', sa.String(), nullable=True))
    op.add_column('slack_bugout_users', sa.Column('bugout_group_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_bugout_users', 'bugout_group_id')
    op.drop_column('github_bugout_users', 'bugout_group_id')
    # ### end Alembic commands ###
