"""Added channel_id column to SlackMention model

Revision ID: f66f6217c742
Revises: d23173c9fd7e
Create Date: 2020-08-04 09:24:37.827812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66f6217c742'
down_revision = 'd23173c9fd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_mentions', sa.Column('channel_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'slack_mentions', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slack_mentions', type_='unique')
    op.drop_column('slack_mentions', 'channel_id')
    # ### end Alembic commands ###
