"""Entry lock

Revision ID: f909b4acb52f
Revises: 245914e1ddf9
Create Date: 2022-09-05 10:25:46.047276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f909b4acb52f'
down_revision = '245914e1ddf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry_locks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('journal_entry_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_journal_entry_locks_journal_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry_locks')),
    sa.UniqueConstraint('id', name=op.f('uq_journal_entry_locks_id')),
    sa.UniqueConstraint('journal_entry_id', name=op.f('uq_journal_entry_locks_journal_entry_id'))
    )
    op.create_index(op.f('ix_journal_entry_locks_locked_at'), 'journal_entry_locks', ['locked_at'], unique=False)
    op.create_index(op.f('ix_journal_entry_locks_locked_by'), 'journal_entry_locks', ['locked_by'], unique=False)
    op.alter_column('journal_ttls', 'journal_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_ttls', 'journal_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_journal_entry_locks_locked_by'), table_name='journal_entry_locks')
    op.drop_index(op.f('ix_journal_entry_locks_locked_at'), table_name='journal_entry_locks')
    op.drop_table('journal_entry_locks')
    # ### end Alembic commands ###
