"""Journal foreign key deletion cascades

Revision ID: fffa1d642e4d
Revises: 2d33cccbba8a
Create Date: 2020-08-11 19:20:29.322121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffa1d642e4d'
down_revision = '2d33cccbba8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_journal_entries_journals_id', 'journal_entries', type_='foreignkey')
    op.create_foreign_key('fk_journal_entries_journals_id', 'journal_entries', 'journals', ['journal_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_journal_entry_tags_journal_entries_id', 'journal_entry_tags', type_='foreignkey')
    op.create_foreign_key('fk_journal_entry_tags_journal_entries_id', 'journal_entry_tags', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_journal_entry_tags_journal_entries_id', 'journal_entry_tags', type_='foreignkey')
    op.create_foreign_key('fk_journal_entry_tags_journal_entries_id', 'journal_entry_tags', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint('fk_journal_entries_journals_id', 'journal_entries', type_='foreignkey')
    op.create_foreign_key('fk_journal_entries_journals_id', 'journal_entries', 'journals', ['journal_id'], ['id'])
    # ### end Alembic commands ###
